### ISSUE TITLE
Extensão não lista todos os projetos alocados

### ISSUE THREAD

**Issue by 0xMur0** [convisolabs/Burp-ConvisoPlatform#10]
Atualmente estou alocado em 2 projetos diferentes dentro do Flow.

![1 - 2 projetos alocados Flow](https://user-images.githubusercontent.com/21301873/143489174-c20abeed-8ccb-4be7-8bf5-4753606e50ea.png)

Porém ao utilizar a extensão, na sessão de Management > Allocated Projects, aparece somente um dos projetos. Se clico em Reload, não acontece mais nada e o botão fica desativado

![2 - Extension 1 projeto listado](https://user-images.githubusercontent.com/21301873/143489178-82ac4522-b9f7-4d80-8152-b236a33e34fe.png)
.

**Comment by rangeldarosa** [comment]
After some investigation, we couldn't conclude exactly what caused this, it suddenly stopped happening. 

This issue will continue open for until 01/01/2022, if it doesn't happen again, it will be closed.
