### ISSUE TITLE
Atualização de logo

### ISSUE THREAD

**Issue by gabogaldino** [convisolabs/Burp-ConvisoPlatform#14]
Olá, criando essa issue aqui para lembrar de atualizar a logo para a nova marca da Conviso.

**Comment by rangeldarosa** [comment]
Olá @gabogaldino tudo bem? De qual logo estamos falando? Você pode criar uma nova branch, fazer o update e então realizar pull request que aprovaremos. 

Muito obrigado!

**Comment by htrgouvea** [comment]
Oi pessoal,

@rangeldarosa seria a nova logo que foi anunciada após o rebrand da Conviso. @gabogaldino já fiz esse PR aqui: #16 

Outra pontuação, acredito que para as issues que forem abertas no futuro, podemos manter o idioma inglês como padrão, assim conseguimos alcançar mais pessoas.
